package egd.covid.persistence.entity;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Entity
@Table(name = "COVID")
public class CovidEntity implements Serializable {
	private static final long serialVersionUID = -8934281800873476677L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID")
	private Long id;

	@Column(name = "ORIGEN")
	private String origen;
	@Column(name = "SECTOR")
	private String sector;
	@Column(name = "ID_REGISTRO")
	private Long idRegistro;
	@Column(name = "CVEENTUNI")
	private Long cveentuni;
	@Column(name = "CVEMUNUNI")
	private Long cvemununi;
	@Column(name = "ENTIDAD")
	private String entidad;
	@Column(name = "DELEGA")
	private String delega;
	@Column(name = "UNIDAD")
	private String unidad;
	@Column(name = "FECHREG")
	private Date fechareg;
	@Column(name = "CLUES")
	private String clues;
	@Column(name = "FOLIO SINAVE")
	private String folioSinave;
	@Column(name = "FOLIO_IMSS")
	private String folioImss;
	@Column(name = "APEPATER")
	private String apepater;
	@Column(name = "APEMATER")
	private String apemater;
	@Column(name = "NOMBRE")
	private String nombre;
	@Column(name = "SEXO")
	private String sexo;
	@Column(name = "CURP")
	private String curp;
	@Column(name = "ENTNACI")
	private String entnaci;
	@Column(name = "ENTRESI")
	private String entresi;
	@Column(name = "CVENTINE")
	private Long cventine;
	@Column(name = "MPIORESI")
	private String mpioresi;
	@Column(name = "CVEMUNI")
	private Long cvemuni;
	@Column(name = "LOCRESI")
	private String locresi;
	@Column(name = "CVELOCAL")
	private Long cvelocal;
	@Column(name = "LATLOCA")
	private Double latloca;
	@Column(name = "LONGLOCA")
	private Double longloca;
	@Column(name = "TIPACIEN")
	private String tipacien;
	@Column(name = "EVOLUCI")
	private String evoluci;
	@Column(name = "FEGRESO")
	private Date fegreso;
	@Column(name = "FECDEF")
	private Date fecdef;
	@Column(name = "SEMDEF")
	private Long semdef;
	@Column(name = "CERTIDEF")
	private String certidef;
	@Column(name = "DEFPORINF")
	private String defporinf;
	@Column(name = "DEFVERIFI")
	private String defverifi;
	@Column(name = "INTUBADO")
	private String intubado;
	@Column(name = "DIGCLINE")
	private String digcline;
	@Column(name = "FECNACI")
	private Date fecnaci;
	@Column(name = "EDAD")
	private Long edad;
	@Column(name = "NACIONA")
	private String naciona;
	@Column(name = "ESTAEMBA")
	private String estaemba;
	@Column(name = "MESESEMB")
	private Long mesesemb;
	@Column(name = "DOMICILIO")
	private String domicilio;
	@Column(name = "CP")
	private String cp;
	@Column(name = "TELEFONO")
	private String telefono;
	@Column(name = "ESINDIGE")
	private String esindige;
	@Column(name = "HABLEIND")
	private String hableind;
	@Column(name = "OCUPACIO")
	private String ocupacio;
	@Column(name = "SERINGRE")
	private String seringre;
	@Column(name = "FECINGRE")
	private Date fecingre;
	@Column(name = "FECINISI")
	private Date fecinsi;
	@Column(name = "DIAGPROB")
	private String diagprob;
	@Column(name = "FIEBRE")
	private String fiebre;
	@Column(name = "TOS")
	private String tos;
	@Column(name = "ODINOGIA")
	private String odinogia;
	@Column(name = "DISNEA")
	private String disnea;
	@Column(name = "IRRITABI")
	private String irritabi;
	@Column(name = "DIARREA")
	private String diarrea;
	@Column(name = "DOTORACI")
	private String dotoraci;
	@Column(name = "CALOFRIOS")
	private String calosfrios;
	@Column(name = "CEFALEA")
	private String cefalea;
	@Column(name = "MIALGIAS")
	private String mialgias;
	@Column(name = "ARTRAL")
	private String artral;
	@Column(name = "ATAEDOGE")
	private String ataedoge;
	@Column(name = "RINORREA")
	private String rinorrea;
	@Column(name = "POLIPNEA")
	private String polipnea;
	@Column(name = "VOMITO")
	private String vomito;
	@Column(name = "DOLABDO")
	private String dolabdo;
	@Column(name = "CONJUN")
	private String conjun;
	@Column(name = "CIANOSIS")
	private String cianosis;
	@Column(name = "INISUBIS")
	private String inisubis;
	@Column(name = "ANOSMIA")
	private String anosmia;
	@Column(name = "DISGEUSIA")
	private String disgeusia;
	@Column(name = "ASINTOMATICO")
	private String asintomatico;
	@Column(name = "DIABETES")
	private String diabetes;
	@Column(name = "EPOC")
	private String epoc;
	@Column(name = "ASMA")
	private String asma;
	@Column(name = "INMUSUPR")
	private String inmusupr;
	@Column(name = "HIPERTEN")
	private String hiperten;
	@Column(name = "OTRACON")
	private String otracon;
	@Column(name = "VIH/SIDA")
	private String vihSida;
	@Column(name = "ENFCARDI")
	private String enfcardio;
	@Column(name = "OBESIDAD")
	private String obesidad;
	@Column(name = "INSRENCR")
	private String insrencr;
	@Column(name = "TABAQUIS")
	private String tabaquis;
	@Column(name = "RECTRATA")
	private String rectrata;
	@Column(name = "TXCROBIA")
	private String txcrobia;
	@Column(name = "TXANTIVI")
	private String txantivi;
	@Column(name = "ANTIVIRA")
	private String antivira;
	@Column(name = "FECINITXANTIVI")
	private Date fecinitxantivi;
	@Column(name = "CONOCASO")
	private String conocaso;
	@Column(name = "CONTAVES")
	private String contaves;
	@Column(name = "CONCERDO")
	private String concerdo;
	@Column(name = "CONANIMA")
	private String conamina;
	@Column(name = "VACUNADO")
	private String vacunado;
	@Column(name = "FECVAEST")
	private String fecvaest;
	@Column(name = "TOMMUE")
	private String tommue;
	@Column(name = "LABORA")
	private String labora;
	@Column(name = "FOLLABOR")
	private String follabor;
	@Column(name = "RESDEFIN")
	private String redesfin;
	@Column(name = "RESDEFIN2")
	private String redesfin2;
	@Column(name = "ESMIGRA")
	private String esmigra;
	@Column(name = "PAISNAL")
	private String paisnal;
	@Column(name = "PAISORI")
	private String paisori;
	@Column(name = "FINGMEX")
	private String fingmex;
	@Column(name = "PAISTRAN1")
	private String paistran1;
	@Column(name = "PAISTRAN2")
	private String paistran2;
	@Column(name = "PAISTRAN3")
	private String paistran3;
	@Column(name = "PAISTRAN4")
	private String paistran4;
	@Column(name = "PUERPERIO")
	private String puerperio;
	@Column(name = "DIASPUERP")
	private String diaspuerp;
	@Column(name = "ANTIPIRETICOS")
	private String antipireticos;
	@Column(name = "UCI")
	private String uci;
	@Column(name = "ORIGEN_DATOS")
	private String origenDatos;
	@Column(name = "ASODIC")
	private String asodic;
	@Column(name = "ANTIGENCOVID")
	private String antigencovid;
	@Column(name = "FECMUEANT")
	private Date fecmueant;
	@Column(name = "CLASCOVID19")
	private String clascovid19;
	@Column(name = "CLASFLU")
	private String claflu;
	@Column(name = "PROTOCOLO")
	private String protocolo;
	@Column(name = "VACUNA_COV")
	private String vacunaCov;
	@Column(name = "TIPO_VAC_COV")
	private String tipoVacCov;
	@Column(name = "FEC_VAC_COV")
	private Date fecVacCov;
	@Column(name = "REF_VAC_COV")
	private String refVacCov;
	@Column(name = "FEC_REF_VAC_COV")
	private Date fecRefVacCov;
	@Column(name = "LINAJE")
	private String linaje;
	@Column(name = "VIAJE1")
	private String viaje1;
	@Column(name = "VIAJE2")
	private String viaje2;
	@Column(name = "VIAJE3")
	private String viaje3;
	@Column(name = "VIAJE4")
	private String viaje4;
	@Column(name = "VIAJE5")
	private String viaje5;
}
